server:
  port: ${PORT:5000}
  # port: 9092

db:
    database: d6k3mh7iegl2mj
    host: ec2-54-235-86-226.compute-1.amazonaws.com
    port: 5432
    username: tieyiexrpkzxop
    password: db828c317d53f062b56aecf8af7230898083a7cbd96f5e3e069beb24052837c7
    
spring:
  datasource:
    url: jdbc:postgresql://ec2-54-235-86-226.compute-1.amazonaws.com:5432/d6k3mh7iegl2mj?useSSL=true&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: tieyiexrpkzxop
    password: db828c317d53f062b56aecf8af7230898083a7cbd96f5e3e069beb24052837c7
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false
      ddl-auto: update
    show-sql: true    

    properties:
      hibernate:
        temp:    
          use_jdbc_metadata_defaults: false

security:
  oauth2:
    resource:
      filter_order: 3

